### ISSUE TITLE
Blank main panel

### ISSUE THREAD

**Issue by bossanova808** [evan-buss/openbooks#101]
Following an alert from diun, I updated my openbooks docker just now.

I now have an empty main pain where the search should be (in dev tools it is empty too...).  
If I minimise the side bar, I then have a totally blank screen...

![image](https://user-images.githubusercontent.com/731309/189037051-4af68403-bc89-4905-aaec-ebc9ee3df5b7.png)

Tested in both Firefox and Chrome.

![image](https://user-images.githubusercontent.com/731309/189037551-a8c7182a-cb82-4ade-afc8-c6b0ba2cfb1a.png)

**Comment by bossanova808** [comment]
Hard refresh, clearing all browser cache/storage, multiple browsers and multiple machines tried (again, but should have mentioned that!).

**Comment by FuncSol** [comment]
I have the same issue. I have a number of saved searches still on the sidebar, & when selecting show results nothing changes.

Inspect shows WebSocket Connected on the console. 

![image](https://user-images.githubusercontent.com/42657022/189249956-ac92f069-0541-417d-93a4-d28379f06769.png)

**Comment by bossanova808** [comment]
@FuncSol Are you also using the docker version, or?

**Comment by FuncSol** [comment]
> @FuncSol Are you also using the docker version, or?

Yes, using the suggested docker-compose, so as "out of the box" as I can manage.

**Comment by FuncSol** [comment]
`#Openbooks Server IRC Client
  openbooks:
      ports:
          - '$OPENBOOKS_WEB_PORT:80'
      volumes:
          - 'booksVolume:/books'
      restart: unless-stopped
      container_name: OpenBooks
      command: --persist
      environment:
        - BASE_PATH=/openbooks/
      image: evanbuss/openbooks:latest`

**Comment by bossanova808** [comment]
Yep my guess is that a dependency for the new UI ('mantine') is not present in the Docker.  But beyond my pay-grade to PR for that as I have never heard of mantine and have only basic Dockerfile knowledge

**Comment by bossanova808** [comment]
This is fixed for me with the new release, thanks @evan-buss
