### ISSUE TITLE
Changing Listen port

### ISSUE THREAD

**Issue by abominalizer** [evan-buss/openbooks#103]
How can I change the listen port from 80 to whatever?

**Comment by evan-buss** [comment]
Using Docker? Just [publish the container port](https://docs.docker.com/config/containers/container-networking/#published-ports) 80 to whatever port you'd like. So if you wanted to run it on port `8080` you'd use `docker run -p 8080:80 evanbuss/openbooks`.

For the executable, use the `--port` flag.
