### ISSUE TITLE
Possibly wrong IRC protocol implementation

### ISSUE THREAD

**Issue by ncryptedV1** [evan-buss/openbooks#107]
The initial `USER` command seems to send the wrong data. According to the [RFC2812](https://datatracker.ietf.org/doc/html/rfc2812#section-3.1.3) the second parameter should most likely be `0` and the third one `*`.
The affected line can be found here: https://github.com/evan-buss/openbooks/blob/91bb21ac7d8d2b09e1117d1a573184b000feadb0/irc/irc.go#L43

**Comment by evan-buss** [comment]
Good catch. Not sure where I got the original message format but it does seem to be incorrect... Do you want to submit a PR?
