### ISSUE TITLE
Client is banned

### ISSUE THREAD

**Issue by TetraTsunami** [evan-buss/openbooks#111]
Hello! I was having issues similar to those described in #70, and followed the suggested steps to produce a log file.
Of particular note are the lines at the end:
```:zathras.mo.us.irchighway.net 366 stable_gallery_1 #ebooks :End of /NAMES list.
:ChanServ!services@services.irchighway.net NOTICE stable_gallery_1 :[#ebooks] [#ebooks] Welcome to #ebooks. Read the channel topic for current information!
:Search!Search@ihw-nrl.5sm.25.50.IP MODE #ebooks +b stable_gallery_1!*able_gall@ihw-t1s.147.235.68.IP
:Search!Search@ihw-nrl.5sm.25.50.IP KICK #ebooks stable_gallery_1 :LazyLibrarian/Openbooks
:zathras.mo.us.irchighway.net 404 stable_gallery_1 #ebooks :Cannot send to channel (no external messages)
```
[Here is the full log](https://github.com/evan-buss/openbooks/files/10322931/stable_gallery_1--2022-12-29--20-59-39.log)
I'm using the latest docker image (albeit with network traffic routed through Mullvad), and my specific setup most recently worked on December 25th. As far as I know I haven't changed anything since. (I'm newish to Github issues, sorry if this is already known)

**Comment by evan-buss** [comment]
> KICK #ebooks stable_gallery_1 :LazyLibrarian/Openbooks

It looks like they set up a block rule for OpenBooks. Strange, as I haven't received any messages from the admins to fix anything.

**Comment by evan-buss** [comment]
Latest release requires manually setting an IRC `--name` and optionally specifying a `--useragent` string. These flags will reduce the chance OpenBooks clients can easily be identified and blocked. See [changelog](https://evan-buss.github.io/openbooks/changelog/).
