### ISSUE TITLE
No books/No Connection?

### ISSUE THREAD

**Issue by VillarosaKeebs** [evan-buss/openbooks#113]
Installed today using docker-compose and Portainer, but when I open the Web UI and look for a book, I just get a never-ending buffering/loading circle and no books show up.  I get an OpenBooks Server Connected on the side so I am unsure as to why this is happening.

**Comment by SirBomble** [comment]
I have the same issue, even when I  compile it from the source.

**Comment by SirBomble** [comment]
Slight update, I did some digging and it seems that the Bot that returns search results via @search doesn't return anything. If anyone could confirm this for me as well it would be appreciated.

**Comment by evan-buss** [comment]
See #70. I think they've recently decided to ban any usernames / user agents in the format OpenBooks uses.

**Comment by SirBomble** [comment]
That's what I thought, but I can't even search using IRC directly, I tested using Pidgin on Pop OS. I'll have to dig into a possible work around, thanks for the response. 

Happy new years!

**Comment by hackmonker** [comment]
lazylibrarian can use our own email and so works. maybe it blocks the email openbooks is using or something?

**Comment by evan-buss** [comment]
Latest release requires manually setting an IRC `--name` and optionally specifying a `--useragent` string. These flags will reduce the chance OpenBooks clients can easily be identified and blocked. See [changelog](https://evan-buss.github.io/openbooks/changelog/).

**Comment by BenRoe** [comment]
Any updates here? Tried —useragent but will not connect.
