### ISSUE TITLE
unknown flag after v4.5.0

### ISSUE THREAD

**Issue by chxseh** [evan-buss/openbooks#119]
Thanks so much for developing OpenBooks, it's very appreciated:)

I've ran into an issue that I can only assume due to my incompetence, however I cannot replicate with a local binary as macOS complains.

I am launching with the following inside Docker:

CMD | --persist --name "user" --useragent "HexChat 2.9.1"
-- | --
ENTRYPOINT | ./openbooks server --dir /books --port 80

Yet I am receiving the following error: `unknown flag: --persist --name "user" --useragent "HexChat 2.9.1"`

Happens both with and without quotes for the strings.

---

It also appears the docs have the wrong flag here (`--username` should be `--useragent`):
https://github.com/evan-buss/openbooks/blob/master/docs/docs/changelog.md?plain=1#L4

**Comment by evan-buss** [comment]
> It also appears the docs have the wrong flag here (--username should be --useragent):
https://github.com/evan-buss/openbooks/blob/master/docs/docs/changelog.md?plain=1#L4

Good catch, I've just fixed it. Thanks!

Your flags look correct, can you provide the full docker run command you are using?
