### ISSUE TITLE
Issues when building

### ISSUE THREAD

**Issue by SmartBoy84** [evan-buss/openbooks#12]
1. In the build.sh you do "cd server/app" and this breaks the whole script as you named it "app_old"
2. packr2 is not up anymore in the path you direc the user to - tell them to instead download the binary from https://github.com/gobuffalo/packr/releases/ and place in $GOBIN
3. tsconfig.app.json config overrides tsconfig.json and results in an error to fix I remove ```"types": []``` from .app.json
4. To access webserver over wan one needs to change ws address in app/src/app.jsx

THIS IS AM AMAZING PROJECT BTW - WELL DONE!

**Comment by SmartBoy84** [comment]
box := packr.New("ReactApp", "./app/build")

Need to set to either "client" or "app_old"
Jeez man...

**Comment by evan-buss** [comment]
Yeah, I was going to swap out the React client for an Angular client but I never completed it. The project isn't really in a buildable state right now. I will look into reverting back to the previous client so it can build and run. Wasn't even sure anyone used it, probably should have made my changes in a separate branch. 😐
