### ISSUE TITLE
Error: required flag(s) "name" not set

### ISSUE THREAD

**Issue by airdogvan** [evan-buss/openbooks#125]
Tried in a very basic docker-compose and came up with this error.
Set NAME=username in the environment but not use.

Any help appreciated.

**Comment by xXAzazelXx** [comment]
I get the same, crashing the container

**Comment by filcuk** [comment]
Can confirm, works fine with the command.
I would suggest including that here to avoid further issues raised: https://github.com/evan-buss/openbooks#docker

**Comment by airdogvan** [comment]
works well for me as well but now the web interface tells me the use I chose is  not connected
