### ISSUE TITLE
Channel Name configurable (Feature Request)

### ISSUE THREAD

**Issue by jonathan-shahen** [evan-buss/openbooks#128]
Right now the channel name is hardcoded, but not all IRCs utilize `#ebooks`, I would like to be able to configure this and the default value to be `ebooks`

The change is: `core/irchighway.go` line 22

**Comment by evan-buss** [comment]
Not sure how useful it would be since we are parsing IRC messages for "IRC Highway specific" response formats. If another server has an ebook channel it probably wouldn't work unless they are sending responses back in the exact same format that IRC Highway uses...
