### ISSUE TITLE
Fix for permanent web app

### ISSUE THREAD

**Issue by SmartBoy84** [evan-buss/openbooks#15]
I've been using this as a webapp hosted on https://books.gabba.ga/

The changes I make were the following:
Auto-selected wss or ws based on html protocol and was window.location.host to find address
IRC seems to time out after a while so I implemented a timer that closes irc connection if no client was connected for 10 minutes.

I'll make a pull request if I figure out how to...
I'm trying currently to recreate this in node js, like you I don't want to use an irc library but rather make my own.
The advantage of making this solely in n-js would be that I can have many concurrent people using the app and the irc connection would be "hosted" locally on their computers

**Comment by SmartBoy84** [comment]
You also don't need the 30 second wait, I have been the app for a while without any repercussions (being banned etc)

**Comment by evan-buss** [comment]
> You also don't need the 30 second wait, I have been the app for a while without any repercussions (being banned etc)

The 30 second wait is there because once you first join the IRC channel, there is a server rule that prevents searching for 30 seconds. If you send a search before time is up, it doesn't go into the queue. Not sure if those rules changed.

**Comment by SmartBoy84** [comment]
#16

**Comment by SmartBoy84** [comment]
The webserver hosting the app is on:
[Book Store](https://books.gabba.ga/)
Excuse me changing the title - if you want me to keep openBooks so to better spread awareness of your project then please tell me! :)
