### ISSUE TITLE
Add a toggle to download via browser

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [evan-buss/openbooks#152]
Currently when the download button is pressed, the book is downloaded in the server location and then a download link pops up as well on the browser window.

Add a toggle for the download to only happen on the server and so no download pop up appears on the browser

**Comment by erkkip** [comment]
Seems to be already implemented here https://github.com/evan-buss/openbooks/pull/87

**Comment by Gandalf-the-Blue** [comment]
I apologize, yes this feature works correctly. I shall close this issue
