### ISSUE TITLE
404 Page not found error

### ISSUE THREAD

**Issue by goaliedude3919** [evan-buss/openbooks#162]
I just tried installing this in Docker and I get a "404 Page not found" error when trying to access http://<server_ip>:<port> or http://<server_ip>:<port>/openbooks. I'm using the following docker compose file:

version: "3.9"
services:
  openbooks:
    image: evanbuss/openbooks:latest
    command:
      - -n <user># REQUIRED - Username used to connect to IRC server
      - --persist
    container_name: OpenBooks
    hostname: openbooks
    security_opt:
      - no-new-privileges:true
    read_only: true
    ports:
      - 6081:80
    volumes:
      - /opt/apps/openbooks:/books:rw
    environment:
      BASE_PATH: /openbooks/
    restart: on-failure:5
networks: {}

-----

The only logs I could find don't have any useful information.

OpenBooks  | 2024/02/29 05:21:09 SERVER: Base Path: /openbooks/
OpenBooks  | 2024/02/29 05:21:09 SERVER: OpenBooks is listening on port 80
OpenBooks  | 2024/02/29 05:21:09 SERVER: Download Directory: /books
OpenBooks  | 2024/02/29 05:21:09 SERVER: Open http://localhost:80/openbooks/ in your browser.

**Comment by evan-buss** [comment]
Remove the BASE_PATH option if you want to access it at the root path of /.

**Comment by goaliedude3919** [comment]
Looks like it was as simple as not having the trailing slash in the URL, thanks!
