### ISSUE TITLE
Calibre Integration?

### ISSUE THREAD

**Issue by vedkothavade** [evan-buss/openbooks#45]
Would integration into an existing Calibre Content Server be possible as it is with [Readarr](https://github.com/Readarr/Readarr)?

**Comment by MrJay84** [comment]
This would be an excellent addition!

**Comment by joelang1699** [comment]
Prowlar integration would be better.

**Comment by vedkothavade** [comment]
> Prowlar integration would be better.

For torrents you might as well use Readarr, and allowing this to also add to Calibre would allow you to use the two tools together easily as the both end books to the same place

**Comment by ljo123** [comment]
Calibre automatic adding via folder monitoring should already allow some integration. However, the books fail to import properly as calibre copies the data out before the download is completed. Is it possible to download with a temporary placeholder name until its complete as this would solve the issue?

**Comment by vedkothavade** [comment]
Maybe instead of a name just a different file extension, like how chrome downloads as .crdownload?

**Comment by ljo123** [comment]
Yeah that would work. I just did a test with a epub re-named to .temp and calibre ignored it.

**Comment by digitalgp** [comment]
the best option is to make openbook as a indexer in prowlarr or second best is to integrate with calibre and&or readarr to make sure the lists are in sync

**Comment by damomato** [comment]
i would also like openbooks to be an indexer for prowlarr if possible

**Comment by MrJay84** [comment]
How do I add this to Prowlarr? I don't see this in the latest release.

**Comment by ljo123** [comment]
> 

There is no prowlarr integration. Your best bet is to use calibre and set up a monitored folder for auto-importing. Then set Openbooks download directory to the same folder. Openbooks downloads it, calibre picks it up and imports.

**Comment by joelang1699** [comment]
Ah okay. Thanks for the info mate.

⁣Get BlueMail for Android ​
