### ISSUE TITLE
Donation Opportunity?

### ISSUE THREAD

**Issue by flickerfly** [evan-buss/openbooks#56]
@evan-buss  I'd like to donate a few bucks to this project on behalf of a friend who appreciates it and had a recent loss. Could I paypal your gmail account or something?

**Comment by evan-buss** [comment]
Hi @flickerfly, sorry to hear about your friend... I do have a PayPal set up with the gmail address on my profile. Feel free to donate; any donations are appreciated but not expected. I'm just happy that others have found this project useful!

**Comment by flickerfly** [comment]
I put $30 in your account and I'll direct my friend here. Not sure he wants to be directly connected.

**Comment by fallenpixel** [comment]
Friend here. Thank you @flickerfly that's very considerate of you. @evan-buss Thank you for the amazing project.
