### ISSUE TITLE
Web UI not working

### ISSUE THREAD

**Issue by miforefox** [evan-buss/openbooks#57]
Hi, from version 3.3.1 and onwards when I run the server through the cmd the browser only shows a blank page. On the contrary when I try to run any version before 3.3.1 the browser shows the expected web ui. Am i doing something wrong?

**Comment by evan-buss** [comment]
If you are on Windows please try [this fix](https://github.com/evan-buss/openbooks/issues/47#issuecomment-1001687622).

**Comment by miforefox** [comment]
Thank you very much! It now works flawlessly!
