### ISSUE TITLE
'Version' inquiries from IRC  servers/client receive silence

### ISSUE THREAD

**Issue by FryMiester** [evan-buss/openbooks#59]
Issue #52 was closed before my reply was read apparently. The 'version' reply doesn't have to have a version number but it needs to reply with -something- other than silence. If it looks like a bot and acts like a bot it will be treated as a bot.

**Comment by evan-buss** [comment]
Is [this](https://en.wikipedia.org/wiki/Client-to-client_protocol#VERSION) the correct format of the response you are expecting?

**Comment by FryMiester** [comment]
The information is correct as it stands but the format is incomplete:
sendToIRC "NOTICE " & Inquirer & " :VERSION " & VersionInformation & ""

If the above control code doesn't render here, it is  ASCII value 0x01

**Comment by FryMiester** [comment]
As the version inquiry is an integral part of FWServerBot version 2.0.75+ and this issue has not yet been resolved, I have ceased doing a manual bypass on OpenBooks clients, they are being ignored by my server software.  I am not trying to be difficult or deny access to anyone regardless of the client they use, it is just what I must do. If you have any questions or suggestions as to how we can address this problem, please feel free to contact me.

**Comment by FryMiester** [comment]
Openbooks users will no longer be an issue in my server software development. I have hard-coded a ban on all Openbooks users in FWServerBot software.  I made a polite and reasonable request that has fallen by the wayside or perhaps thanks to meddling of fruitloops has been ignored.  There are more than one servers using this server software.

**Comment by evan-buss** [comment]
I'm sorry that it's come that that. I have limited free time to work on this program as we are out of the holiday season. I was under the impression that you would continue to block any OpenBooks clients until I added the CTCP VERSION response, I didn't know that time was of the essence. 

Would you permit OpenBooks access to servers running your software if this was added in a future release? Or is the bridge completely burned? Thanks

**Comment by FryMiester** [comment]
I understand limited free time, I have little of my own and have found myself burning the midnight oil. I have made considerable changes to operation of my software in that a CTCP VERSION response failure no longer causes issues, and is no longer required to download from my server... it is only used in case of download failures now.  OpenBooks may access my software as if any other manner of client.  That said, you should continue to add the CTCP Version response to your software as a further manner of identification for software that requests it.
