### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Somnathjanakoti** [evan-buss/openbooks#62]
We can do searching but we are unable to download the file . Before MrAtoz one was very useful to download now none of the link is working . please fix this issue
![Screenshot (39)](https://user-images.githubusercontent.com/41386617/150296160-ced66b8e-13a6-4204-96d4-f8595f9fa1df.png)
Here is the screenshot where the script is running from 30 min still it not downloaded.

**Comment by TPOSD** [comment]
yeah, I got the same problem and I'm using the browser version currently.
Sometimes It works, but most download selections just hang and nothing eventuates.

**Comment by FryMiester** [comment]
Have you considered that the server you are requesting from is Offline? MrAtoz has been MIA for several days.  Other servers may be set to ignore certain behaviors or lack thereof.

**Comment by Somnathjanakoti** [comment]
@FryMiester Yes i tried other servers too none of them are responding.

**Comment by Somnathjanakoti** [comment]
@TPOSD hey , can you tell me how to use browser version .  What to do next after typing "openbooks server " .
