### ISSUE TITLE
Nothing happens after searching

### ISSUE THREAD

**Issue by nithin-bose** [evan-buss/openbooks#70]
I get the connected to server message and I do get a nick which appears at the bottom left. 

However on searching anything, I get a "search request sent" and then nothing happens. The search term appears on the left side of the screen with a spinner and nothing else happens. It just stays like that forever. No errors or results.

I am using the latest docker image of openbooks in a docker compose file like the example given in docker hub with the ``--persist`` command. The following is all I see in the logs:
```
openbooks  | 2022/02/13 21:15:43 SERVER: Base Path: /
openbooks  | 2022/02/13 21:15:43 SERVER: OpenBooks is listening on port 80
openbooks  | 2022/02/13 21:16:41 SERVER: Client connected from 172.18.0.2:37748
openbooks  | 2022/02/13 21:16:41 CLIENT (official_paul_1): New client created.
openbooks  | 2022/02/13 21:16:41 CLIENT (official_paul_1): CONNECT Message Received
openbooks  | 2022/02/13 21:16:53 CLIENT (official_paul_1): SEARCH Message Received
```

Please help

**Comment by evan-buss** [comment]
Sounds like an issue with the IRC server. Can you run the docker image with the `--log` command and add a volume binding. You should see a folder called logs that will show you all the messages received from IRC. Perhaps the name is already in use or your IP was banned.

**Comment by nithin-bose** [comment]
Which path in the container should I bind the volume to?

**Comment by evan-buss** [comment]
`docker run -p 8080:80 -v /your_path_here:/books evanbuss/openbooks --persist --log`

**Comment by ricktoronto** [comment]
This is not an error.  OPENBOOKS CLI is now being banned again as it does not satisfy the agreement made with the channel.  In addition, Openbooks users are being banned from searching when they bypass the search time limits set by the application.  Evan was asked to review and fix the later, but did not reply to the email sent.

The only fix that is acceptable now is that openbooks responds to the irc command VERSION and only approved ones will be accepted at the channel. 

Evan, you know how to get in touch with me :)

**Comment by slarrain** [comment]
> is now being banned again as it does not satisfy the agreement made with the channel. In addition, Openbooks users are being banned from searching when they bypass the search time limits set by the application. 

Sorry for jumping in on a closed issue with a question from a different project, but is this the same that is happening with [LazyLibrarian](https://gitlab.com/LazyLibrarian/LazyLibrarian) @ricktoronto ?

**Comment by slarrain** [comment]
> LazyLibrarian is permanently banned from the channel. This will not change.

That sucks. I think it would be a great integration. I was actually looking at the code of LazyLibrarian and the Issues when they implemented IRC Download, and they were very aware of putting limits to the calls, as to not flood the channel. The code indeed has a wait/.sleep period between calls.

Perhaps there were some issues and the developer did not get your attempts at communicating? Is this something we might be able to open again and explore? I would love to contribute to LazyLibrarian standards/waits/protocols/order to adhere to the channel's rules and be able to use it with LazyLibrarian. Please let me know if this is something we can workout (I'm no developer of any library, just a user that believe you have every right to enforce your own rules and would like to try to make it work with LazyLibrarian). Thanks!

---

Again, sorry Evan for hijacking the thread, but I don't know how else to get in touch with @ricktoronto . By the way, Openbooks works great and I love it. Thanks!

**Comment by ricktoronto** [comment]
We will not be revisiting the position.

**Comment by philborman** [comment]
Hi, I am the current dev for lazylibrarian. I have had no contact from any IRC channels about this block. Could you please contact me via the lazylibrarian gitlab site https://gitlab.com/LazyLibrarian/LazyLibrarian/-/issues. I think the current code should be compliant and maybe we can discuss additional testing and removing the block? Thanks

**Comment by ricktoronto** [comment]
We attempted to contact you several times over the past year with no response.  Perhaps it was missed.

Please contact fruitloops in the channel to discuss.
