### ISSUE TITLE
Add CLI option to customise Whois IRC string

### ISSUE THREAD

**Issue by AdrianSimionov** [evan-buss/openbooks#99]

**Comment by evan-buss** [comment]
See response [here](https://github.com/evan-buss/openbooks/issues/98#issuecomment-1239355027). I don't want users to be able to change the WHOIS value as it's a way for the IRC admins to identify OpenBooks users. The success of this project relies on the goodwill of the admins, so limiting the possibility for abuse is especially important.

**Comment by evan-buss** [comment]
Added `--useragent` flag to optionally specify the CTCP VERSION reponse in the latest release.
